2022-12-21 18:28:09,401 - [INFO] 2019/10/12のレースデータの取得を開始します
2022-12-21 18:28:11,508 - [INFO] 取得レース数：12
2022-12-21 18:28:33,744 - [ERROR] 京都05R(race_id:201908040305)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201908040305
2022-12-21 18:28:33,744 - [ERROR] string indices must be integers
2022-12-21 18:28:33,744 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers
2022-12-21 22:26:18,390 - [INFO] 2018/12/23のレースデータの取得を開始します
2022-12-21 22:26:20,483 - [INFO] 取得レース数：24
2022-12-21 22:26:33,213 - [ERROR] 中山03R(race_id:201806050803)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201806050803
2022-12-21 22:26:33,213 - [ERROR] string indices must be integers
2022-12-21 22:26:33,213 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-22 00:09:07,506 - [INFO] 2018/08/19のレースデータの取得を開始します
2022-12-22 00:09:09,628 - [INFO] 取得レース数：36
2022-12-22 00:10:08,620 - [ERROR] 新潟12R(race_id:201804020812)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201804020812
2022-12-22 00:10:08,620 - [ERROR] string indices must be integers
2022-12-22 00:10:08,620 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-22 01:30:43,064 - [INFO] 2018/05/13のレースデータの取得を開始します
2022-12-22 01:30:45,213 - [INFO] 取得レース数：36
2022-12-22 01:31:18,150 - [ERROR] 東京07R(race_id:201805020807)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201805020807
2022-12-22 01:31:18,150 - [ERROR] string indices must be integers
2022-12-22 01:31:18,150 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-22 01:43:17,824 - [INFO] 2018/04/29のレースデータの取得を開始します
2022-12-22 01:43:19,966 - [INFO] 取得レース数：36
2022-12-22 01:44:51,696 - [ERROR] 京都06R(race_id:201808030406)のレース結果取得処理でエラー
2022-12-22 01:44:51,696 - [ERROR] '11'
2022-12-22 01:44:51,696 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '11'

2022-12-22 02:51:29,380 - [INFO] 2018/02/12のレースデータの取得を開始します
2022-12-22 02:51:31,453 - [INFO] 取得レース数：12
2022-12-22 02:51:39,232 - [ERROR] 東京02R(race_id:201805010602)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201805010602
2022-12-22 02:51:39,232 - [ERROR] string indices must be integers
2022-12-22 02:51:39,232 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-22 02:52:30,948 - [ERROR] 東京12R(race_id:201805010612)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201805010612
2022-12-22 02:52:30,948 - [ERROR] string indices must be integers
2022-12-22 02:52:30,948 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-22 02:52:36,577 - [INFO] 2018/02/11のレースデータの取得を開始します
2022-12-22 02:52:38,695 - [INFO] 取得レース数：24
2022-12-22 02:53:38,290 - [ERROR] 東京12R(race_id:201805010512)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201805010512
2022-12-22 02:53:38,290 - [ERROR] string indices must be integers
2022-12-22 02:53:38,290 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-22 02:54:39,915 - [ERROR] 京都12R(race_id:201808020612)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201808020612
2022-12-22 02:54:39,915 - [ERROR] string indices must be integers
2022-12-22 02:54:39,915 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-22 02:54:45,748 - [INFO] 2018/02/10のレースデータの取得を開始します
2022-12-22 02:54:47,866 - [INFO] 取得レース数：24
2022-12-22 02:55:46,246 - [ERROR] 京都12R(race_id:201808020512)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201808020512
2022-12-22 02:55:46,246 - [ERROR] string indices must be integers
2022-12-22 02:55:46,246 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-22 02:56:48,479 - [ERROR] 小倉12R(race_id:201810010112)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201810010112
2022-12-22 02:56:48,480 - [ERROR] string indices must be integers
2022-12-22 02:56:48,480 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-22 03:04:11,850 - [INFO] 2018/01/27のレースデータの取得を開始します
2022-12-22 03:04:13,964 - [INFO] 取得レース数：36
2022-12-22 03:04:49,422 - [ERROR] 東京07R(race_id:201805010107)のレース結果取得処理でエラー
2022-12-22 03:04:49,422 - [ERROR] '12'
2022-12-22 03:04:49,422 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '12'

2022-12-22 03:30:29,324 - [INFO] 2017/12/23のレースデータの取得を開始します
2022-12-22 03:30:31,418 - [INFO] 取得レース数：24
2022-12-22 03:32:02,714 - [ERROR] 阪神06R(race_id:201709050706)のレース結果取得処理でエラー
2022-12-22 03:32:02,714 - [ERROR] '14'
2022-12-22 03:32:02,714 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '14'

2022-12-22 20:49:18,703 - [INFO] 2014/07/19のレースデータの取得を開始します
2022-12-22 20:49:20,865 - [INFO] 取得レース数：36
2022-12-22 20:50:03,711 - [ERROR] 中京09R(race_id:201407030509)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201407030509
2022-12-22 20:50:03,711 - [ERROR] '18'
2022-12-22 20:50:03,711 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-22 21:17:29,181 - [INFO] 2014/06/15のレースデータの取得を開始します
2022-12-22 21:17:31,318 - [INFO] 取得レース数：36
2022-12-22 21:18:20,377 - [ERROR] 東京10R(race_id:201405030410)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201405030410
2022-12-22 21:18:20,377 - [ERROR] '18'
2022-12-22 21:18:20,377 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-22 23:19:33,313 - [INFO] 2014/01/19のレースデータの取得を開始します
2022-12-22 23:19:35,420 - [INFO] 取得レース数：36
2022-12-22 23:19:37,804 - [ERROR] 中山01R(race_id:201406010701)の馬柱取得処理でエラー
2022-12-22 23:19:37,804 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:19:37,804 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:19:45,446 - [ERROR] 中山03R(race_id:201406010703)の馬柱取得処理でエラー
2022-12-22 23:19:45,446 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:19:45,446 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:19:48,210 - [ERROR] 中山04R(race_id:201406010704)の馬柱取得処理でエラー
2022-12-22 23:19:48,210 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:19:48,211 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:19:50,804 - [ERROR] 中山05R(race_id:201406010705)の馬柱取得処理でエラー
2022-12-22 23:19:50,804 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:19:50,804 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:19:53,363 - [ERROR] 中山06R(race_id:201406010706)の馬柱取得処理でエラー
2022-12-22 23:19:53,363 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:19:53,363 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:19:56,014 - [ERROR] 中山07R(race_id:201406010707)の馬柱取得処理でエラー
2022-12-22 23:19:56,014 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:19:56,014 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:19:58,935 - [ERROR] 中山08R(race_id:201406010708)の馬柱取得処理でエラー
2022-12-22 23:19:58,936 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:19:58,936 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:16,888 - [ERROR] 中山12R(race_id:201406010712)の馬柱取得処理でエラー
2022-12-22 23:20:16,888 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:16,888 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:19,553 - [ERROR] 京都01R(race_id:201408010701)の馬柱取得処理でエラー
2022-12-22 23:20:19,553 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:19,553 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:22,159 - [ERROR] 京都02R(race_id:201408010702)の馬柱取得処理でエラー
2022-12-22 23:20:22,159 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:22,160 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:24,779 - [ERROR] 京都03R(race_id:201408010703)の馬柱取得処理でエラー
2022-12-22 23:20:24,780 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:24,780 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:27,420 - [ERROR] 京都04R(race_id:201408010704)の馬柱取得処理でエラー
2022-12-22 23:20:27,420 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:27,420 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:30,113 - [ERROR] 京都05R(race_id:201408010705)の馬柱取得処理でエラー
2022-12-22 23:20:30,113 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:30,113 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:33,062 - [ERROR] 京都06R(race_id:201408010706)の馬柱取得処理でエラー
2022-12-22 23:20:33,062 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:33,062 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:35,968 - [ERROR] 京都07R(race_id:201408010707)の馬柱取得処理でエラー
2022-12-22 23:20:35,968 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:35,968 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:38,710 - [ERROR] 京都08R(race_id:201408010708)の馬柱取得処理でエラー
2022-12-22 23:20:38,710 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:38,710 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:56,822 - [ERROR] 京都12R(race_id:201408010712)の馬柱取得処理でエラー
2022-12-22 23:20:56,822 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:56,822 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:20:59,531 - [ERROR] 中京01R(race_id:201407010201)の馬柱取得処理でエラー
2022-12-22 23:20:59,531 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:20:59,531 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:21:02,339 - [ERROR] 中京02R(race_id:201407010202)の馬柱取得処理でエラー
2022-12-22 23:21:02,339 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:21:02,339 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:21:05,313 - [ERROR] 中京03R(race_id:201407010203)の馬柱取得処理でエラー
2022-12-22 23:21:05,313 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:21:05,313 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:21:08,172 - [ERROR] 中京04R(race_id:201407010204)の馬柱取得処理でエラー
2022-12-22 23:21:08,172 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:21:08,172 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:21:10,810 - [ERROR] 中京05R(race_id:201407010205)の馬柱取得処理でエラー
2022-12-22 23:21:10,810 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:21:10,811 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:21:13,645 - [ERROR] 中京06R(race_id:201407010206)の馬柱取得処理でエラー
2022-12-22 23:21:13,645 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:21:13,645 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:21:16,394 - [ERROR] 中京07R(race_id:201407010207)の馬柱取得処理でエラー
2022-12-22 23:21:16,394 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:21:16,394 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:21:19,345 - [ERROR] 中京08R(race_id:201407010208)の馬柱取得処理でエラー
2022-12-22 23:21:19,345 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:21:19,345 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:21:22,308 - [ERROR] 中京09R(race_id:201407010209)の馬柱取得処理でエラー
2022-12-22 23:21:22,309 - [ERROR] invalid literal for int() with base 10: ''
2022-12-22 23:21:22,309 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 92, in main
    self.get_umabashira()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 303, in get_umabashira
    self.race_info.run_num = str(int(self.race_info.regist_num) - len(cancel_num))
ValueError: invalid literal for int() with base 10: ''

2022-12-22 23:44:49,726 - [INFO] 2013/12/14のレースデータの取得を開始します
2022-12-22 23:44:51,834 - [INFO] 取得レース数：36
2022-12-22 23:47:29,926 - [ERROR] 中京08R(race_id:201307040508)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201307040508
2022-12-22 23:47:29,927 - [ERROR] '18'
2022-12-22 23:47:29,927 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-23 01:19:56,939 - [INFO] 2013/08/18のレースデータの取得を開始します
2022-12-23 01:19:59,078 - [INFO] 取得レース数：36
2022-12-23 01:20:47,855 - [ERROR] 新潟10R(race_id:201304020810)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201304020810
2022-12-23 01:20:47,856 - [ERROR] '18'
2022-12-23 01:20:47,856 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-23 02:00:24,917 - [INFO] 2013/07/06のレースデータの取得を開始します
2022-12-23 02:00:27,024 - [INFO] 取得レース数：36
2022-12-23 02:00:54,441 - [ERROR] 中京06R(race_id:201307030306)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201307030306
2022-12-23 02:00:54,441 - [ERROR] '18'
2022-12-23 02:00:54,441 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-23 02:38:07,731 - [INFO] 2013/05/18のレースデータの取得を開始します
2022-12-23 02:38:09,870 - [INFO] 取得レース数：36
2022-12-23 02:38:58,056 - [ERROR] 東京10R(race_id:201305020910)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201305020910
2022-12-23 02:38:58,056 - [ERROR] '18'
2022-12-23 02:38:58,056 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-23 09:27:38,018 - [INFO] 2012/01/14のレースデータの取得を開始します
2022-12-23 09:27:40,130 - [INFO] 取得レース数：36
2022-12-23 09:30:35,613 - [ERROR] 小倉11R(race_id:201210010111)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201210010111
2022-12-23 09:30:35,613 - [ERROR] '18'
2022-12-23 09:30:35,613 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-23 10:27:01,074 - [INFO] 2011/10/30のレースデータの取得を開始します
2022-12-23 10:27:03,254 - [INFO] 取得レース数：36
2022-12-23 10:29:43,446 - [ERROR] 新潟08R(race_id:201104050608)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201104050608
2022-12-23 10:29:43,446 - [ERROR] '18'
2022-12-23 10:29:43,446 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-23 14:43:54,907 - [INFO] 2010/12/19のレースデータの取得を開始します
2022-12-23 14:43:57,108 - [INFO] 取得レース数：36
2022-12-23 14:46:52,187 - [ERROR] 小倉11R(race_id:201010030611)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=201010030611
2022-12-23 14:46:52,187 - [ERROR] '18'
2022-12-23 14:46:52,187 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-23 15:02:40,735 - [INFO] 2010/11/28のレースデータの取得を開始します
2022-12-23 15:02:42,856 - [INFO] 取得レース数：23
2022-12-23 15:03:33,548 - [ERROR] 東京10R(race_id:201005050810)のレース結果取得処理でエラー
2022-12-23 15:03:33,548 - [ERROR] '18'
2022-12-23 15:03:33,548 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '18'

2022-12-23 15:06:49,860 - [INFO] 2010/11/21のレースデータの取得を開始します
2022-12-23 15:06:52,004 - [INFO] 取得レース数：36
2022-12-23 15:08:47,926 - [ERROR] 京都11R(race_id:201008060611)のレース結果取得処理でエラー
2022-12-23 15:08:47,927 - [ERROR] '18'
2022-12-23 15:08:47,927 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '18'

2022-12-23 16:05:15,918 - [INFO] 2010/09/12のレースデータの取得を開始します
2022-12-23 16:05:18,030 - [INFO] 取得レース数：36
2022-12-23 16:07:07,021 - [ERROR] 阪神10R(race_id:201009040210)のレース結果取得処理でエラー
2022-12-23 16:07:07,022 - [ERROR] '16'
2022-12-23 16:07:07,022 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '16'

2022-12-23 20:06:15,613 - [INFO] 2009/11/22のレースデータの取得を開始します
2022-12-23 20:06:17,762 - [INFO] 取得レース数：36
2022-12-23 20:08:14,687 - [ERROR] 京都11R(race_id:200908050611)のレース結果取得処理でエラー
2022-12-23 20:08:14,687 - [ERROR] '18'
2022-12-23 20:08:14,688 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '18'

2022-12-24 02:34:19,083 - [INFO] 2008/08/16のレースデータの取得を開始します
2022-12-24 02:34:21,190 - [INFO] 取得レース数：36
2022-12-24 02:34:53,716 - [ERROR] 新潟07R(race_id:200804030107)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804030107
2022-12-24 02:34:53,717 - [ERROR] '18'
2022-12-24 02:34:53,717 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-24 02:59:16,570 - [INFO] 2008/07/19のレースデータの取得を開始します
2022-12-24 02:59:18,710 - [INFO] 取得レース数：36
2022-12-24 03:00:02,238 - [ERROR] 新潟09R(race_id:200804020109)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804020109
2022-12-24 03:00:02,238 - [ERROR] '18'
2022-12-24 03:00:02,238 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-24 03:00:07,262 - [ERROR] 新潟10R(race_id:200804020110)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804020110
2022-12-24 03:00:07,262 - [ERROR] '18'
2022-12-24 03:00:07,262 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-24 03:59:03,710 - [INFO] 2008/05/04のレースデータの取得を開始します
2022-12-24 03:59:05,850 - [INFO] 取得レース数：36
2022-12-24 03:59:08,462 - [ERROR] 東京01R(race_id:200805020401)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020401
2022-12-24 03:59:08,462 - [ERROR] string indices must be integers
2022-12-24 03:59:08,462 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 03:59:13,681 - [ERROR] 東京02R(race_id:200805020402)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020402
2022-12-24 03:59:13,681 - [ERROR] string indices must be integers
2022-12-24 03:59:13,681 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 03:59:19,174 - [ERROR] 東京03R(race_id:200805020403)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020403
2022-12-24 03:59:19,174 - [ERROR] string indices must be integers
2022-12-24 03:59:19,174 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 03:59:24,251 - [ERROR] 東京04R(race_id:200805020404)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020404
2022-12-24 03:59:24,251 - [ERROR] string indices must be integers
2022-12-24 03:59:24,251 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 03:59:29,510 - [ERROR] 東京05R(race_id:200805020405)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020405
2022-12-24 03:59:29,511 - [ERROR] string indices must be integers
2022-12-24 03:59:29,511 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 03:59:34,838 - [ERROR] 東京06R(race_id:200805020406)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020406
2022-12-24 03:59:34,838 - [ERROR] string indices must be integers
2022-12-24 03:59:34,838 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 03:59:40,004 - [ERROR] 東京07R(race_id:200805020407)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020407
2022-12-24 03:59:40,004 - [ERROR] string indices must be integers
2022-12-24 03:59:40,004 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 03:59:45,397 - [ERROR] 東京08R(race_id:200805020408)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020408
2022-12-24 03:59:45,397 - [ERROR] string indices must be integers
2022-12-24 03:59:45,398 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 03:59:50,532 - [ERROR] 東京09R(race_id:200805020409)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020409
2022-12-24 03:59:50,532 - [ERROR] string indices must be integers
2022-12-24 03:59:50,532 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 03:59:56,091 - [ERROR] 東京10R(race_id:200805020410)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020410
2022-12-24 03:59:56,091 - [ERROR] string indices must be integers
2022-12-24 03:59:56,091 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:01,659 - [ERROR] 東京11R(race_id:200805020411)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020411
2022-12-24 04:00:01,659 - [ERROR] string indices must be integers
2022-12-24 04:00:01,659 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:07,153 - [ERROR] 東京12R(race_id:200805020412)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020412
2022-12-24 04:00:07,154 - [ERROR] string indices must be integers
2022-12-24 04:00:07,154 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:12,284 - [ERROR] 京都01R(race_id:200808030401)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030401
2022-12-24 04:00:12,284 - [ERROR] string indices must be integers
2022-12-24 04:00:12,284 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:17,682 - [ERROR] 京都02R(race_id:200808030402)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030402
2022-12-24 04:00:17,682 - [ERROR] string indices must be integers
2022-12-24 04:00:17,682 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:22,955 - [ERROR] 京都03R(race_id:200808030403)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030403
2022-12-24 04:00:22,955 - [ERROR] string indices must be integers
2022-12-24 04:00:22,956 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:28,485 - [ERROR] 京都04R(race_id:200808030404)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030404
2022-12-24 04:00:28,485 - [ERROR] string indices must be integers
2022-12-24 04:00:28,485 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:33,624 - [ERROR] 京都05R(race_id:200808030405)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030405
2022-12-24 04:00:33,624 - [ERROR] string indices must be integers
2022-12-24 04:00:33,624 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:39,125 - [ERROR] 京都06R(race_id:200808030406)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030406
2022-12-24 04:00:39,125 - [ERROR] string indices must be integers
2022-12-24 04:00:39,125 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:44,462 - [ERROR] 京都07R(race_id:200808030407)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030407
2022-12-24 04:00:44,463 - [ERROR] string indices must be integers
2022-12-24 04:00:44,463 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:49,856 - [ERROR] 京都08R(race_id:200808030408)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030408
2022-12-24 04:00:49,856 - [ERROR] string indices must be integers
2022-12-24 04:00:49,856 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:00:55,190 - [ERROR] 京都09R(race_id:200808030409)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030409
2022-12-24 04:00:55,190 - [ERROR] string indices must be integers
2022-12-24 04:00:55,190 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:00,472 - [ERROR] 京都10R(race_id:200808030410)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030410
2022-12-24 04:01:00,472 - [ERROR] string indices must be integers
2022-12-24 04:01:00,473 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:05,745 - [ERROR] 京都11R(race_id:200808030411)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030411
2022-12-24 04:01:05,745 - [ERROR] string indices must be integers
2022-12-24 04:01:05,745 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:10,935 - [ERROR] 京都12R(race_id:200808030412)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030412
2022-12-24 04:01:10,935 - [ERROR] string indices must be integers
2022-12-24 04:01:10,935 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:16,251 - [ERROR] 新潟01R(race_id:200804010201)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010201
2022-12-24 04:01:16,251 - [ERROR] string indices must be integers
2022-12-24 04:01:16,251 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:21,492 - [ERROR] 新潟02R(race_id:200804010202)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010202
2022-12-24 04:01:21,492 - [ERROR] string indices must be integers
2022-12-24 04:01:21,492 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:26,629 - [ERROR] 新潟03R(race_id:200804010203)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010203
2022-12-24 04:01:26,629 - [ERROR] string indices must be integers
2022-12-24 04:01:26,629 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:31,839 - [ERROR] 新潟04R(race_id:200804010204)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010204
2022-12-24 04:01:31,839 - [ERROR] string indices must be integers
2022-12-24 04:01:31,839 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:36,931 - [ERROR] 新潟05R(race_id:200804010205)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010205
2022-12-24 04:01:36,931 - [ERROR] string indices must be integers
2022-12-24 04:01:36,931 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:42,057 - [ERROR] 新潟06R(race_id:200804010206)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010206
2022-12-24 04:01:42,057 - [ERROR] string indices must be integers
2022-12-24 04:01:42,057 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:47,142 - [ERROR] 新潟07R(race_id:200804010207)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010207
2022-12-24 04:01:47,142 - [ERROR] string indices must be integers
2022-12-24 04:01:47,142 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:52,378 - [ERROR] 新潟08R(race_id:200804010208)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010208
2022-12-24 04:01:52,378 - [ERROR] string indices must be integers
2022-12-24 04:01:52,378 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:01:57,760 - [ERROR] 新潟09R(race_id:200804010209)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010209
2022-12-24 04:01:57,760 - [ERROR] string indices must be integers
2022-12-24 04:01:57,760 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:02:03,116 - [ERROR] 新潟10R(race_id:200804010210)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010210
2022-12-24 04:02:03,116 - [ERROR] string indices must be integers
2022-12-24 04:02:03,116 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:02:08,343 - [ERROR] 新潟11R(race_id:200804010211)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010211
2022-12-24 04:02:08,343 - [ERROR] string indices must be integers
2022-12-24 04:02:08,343 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:02:13,909 - [ERROR] 新潟12R(race_id:200804010212)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010212
2022-12-24 04:02:13,909 - [ERROR] string indices must be integers
2022-12-24 04:02:13,909 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:02:19,713 - [INFO] 2008/05/03のレースデータの取得を開始します
2022-12-24 04:02:21,821 - [INFO] 取得レース数：36
2022-12-24 04:02:24,472 - [ERROR] 東京01R(race_id:200805020301)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020301
2022-12-24 04:02:24,473 - [ERROR] string indices must be integers
2022-12-24 04:02:24,473 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:02:29,812 - [ERROR] 東京02R(race_id:200805020302)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020302
2022-12-24 04:02:29,812 - [ERROR] string indices must be integers
2022-12-24 04:02:29,812 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:02:34,950 - [ERROR] 東京03R(race_id:200805020303)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020303
2022-12-24 04:02:34,951 - [ERROR] string indices must be integers
2022-12-24 04:02:34,951 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:02:40,189 - [ERROR] 東京04R(race_id:200805020304)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020304
2022-12-24 04:02:40,189 - [ERROR] string indices must be integers
2022-12-24 04:02:40,189 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:02:45,377 - [ERROR] 東京05R(race_id:200805020305)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020305
2022-12-24 04:02:45,377 - [ERROR] string indices must be integers
2022-12-24 04:02:45,377 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:02:50,557 - [ERROR] 東京06R(race_id:200805020306)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020306
2022-12-24 04:02:50,557 - [ERROR] string indices must be integers
2022-12-24 04:02:50,557 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:02:55,876 - [ERROR] 東京07R(race_id:200805020307)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020307
2022-12-24 04:02:55,876 - [ERROR] string indices must be integers
2022-12-24 04:02:55,876 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:01,361 - [ERROR] 東京08R(race_id:200805020308)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020308
2022-12-24 04:03:01,361 - [ERROR] string indices must be integers
2022-12-24 04:03:01,361 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:06,393 - [ERROR] 東京09R(race_id:200805020309)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020309
2022-12-24 04:03:06,393 - [ERROR] string indices must be integers
2022-12-24 04:03:06,393 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:11,759 - [ERROR] 東京10R(race_id:200805020310)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020310
2022-12-24 04:03:11,759 - [ERROR] string indices must be integers
2022-12-24 04:03:11,759 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:16,884 - [ERROR] 東京11R(race_id:200805020311)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020311
2022-12-24 04:03:16,884 - [ERROR] string indices must be integers
2022-12-24 04:03:16,884 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:22,421 - [ERROR] 東京12R(race_id:200805020312)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200805020312
2022-12-24 04:03:22,421 - [ERROR] string indices must be integers
2022-12-24 04:03:22,421 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:27,774 - [ERROR] 京都01R(race_id:200808030301)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030301
2022-12-24 04:03:27,774 - [ERROR] string indices must be integers
2022-12-24 04:03:27,774 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:32,879 - [ERROR] 京都02R(race_id:200808030302)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030302
2022-12-24 04:03:32,880 - [ERROR] string indices must be integers
2022-12-24 04:03:32,880 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:38,274 - [ERROR] 京都03R(race_id:200808030303)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030303
2022-12-24 04:03:38,274 - [ERROR] string indices must be integers
2022-12-24 04:03:38,274 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:43,745 - [ERROR] 京都04R(race_id:200808030304)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030304
2022-12-24 04:03:43,746 - [ERROR] string indices must be integers
2022-12-24 04:03:43,746 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:48,746 - [ERROR] 京都05R(race_id:200808030305)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030305
2022-12-24 04:03:48,746 - [ERROR] string indices must be integers
2022-12-24 04:03:48,746 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:53,949 - [ERROR] 京都06R(race_id:200808030306)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030306
2022-12-24 04:03:53,949 - [ERROR] string indices must be integers
2022-12-24 04:03:53,949 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:03:59,111 - [ERROR] 京都07R(race_id:200808030307)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030307
2022-12-24 04:03:59,111 - [ERROR] string indices must be integers
2022-12-24 04:03:59,111 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:04,452 - [ERROR] 京都08R(race_id:200808030308)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030308
2022-12-24 04:04:04,452 - [ERROR] string indices must be integers
2022-12-24 04:04:04,452 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:09,915 - [ERROR] 京都09R(race_id:200808030309)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030309
2022-12-24 04:04:09,915 - [ERROR] string indices must be integers
2022-12-24 04:04:09,915 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:15,181 - [ERROR] 京都10R(race_id:200808030310)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030310
2022-12-24 04:04:15,181 - [ERROR] string indices must be integers
2022-12-24 04:04:15,181 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:20,745 - [ERROR] 京都11R(race_id:200808030311)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030311
2022-12-24 04:04:20,745 - [ERROR] string indices must be integers
2022-12-24 04:04:20,746 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:25,966 - [ERROR] 京都12R(race_id:200808030312)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808030312
2022-12-24 04:04:25,967 - [ERROR] string indices must be integers
2022-12-24 04:04:25,967 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:31,022 - [ERROR] 新潟01R(race_id:200804010101)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010101
2022-12-24 04:04:31,022 - [ERROR] string indices must be integers
2022-12-24 04:04:31,022 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:36,382 - [ERROR] 新潟02R(race_id:200804010102)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010102
2022-12-24 04:04:36,382 - [ERROR] string indices must be integers
2022-12-24 04:04:36,382 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:41,621 - [ERROR] 新潟03R(race_id:200804010103)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010103
2022-12-24 04:04:41,621 - [ERROR] string indices must be integers
2022-12-24 04:04:41,621 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:46,629 - [ERROR] 新潟04R(race_id:200804010104)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010104
2022-12-24 04:04:46,630 - [ERROR] string indices must be integers
2022-12-24 04:04:46,630 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:51,688 - [ERROR] 新潟05R(race_id:200804010105)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010105
2022-12-24 04:04:51,688 - [ERROR] string indices must be integers
2022-12-24 04:04:51,688 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:04:56,748 - [ERROR] 新潟06R(race_id:200804010106)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010106
2022-12-24 04:04:56,748 - [ERROR] string indices must be integers
2022-12-24 04:04:56,748 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:05:02,260 - [ERROR] 新潟07R(race_id:200804010107)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010107
2022-12-24 04:05:02,261 - [ERROR] string indices must be integers
2022-12-24 04:05:02,261 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:05:07,640 - [ERROR] 新潟08R(race_id:200804010108)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010108
2022-12-24 04:05:07,640 - [ERROR] string indices must be integers
2022-12-24 04:05:07,640 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:05:12,924 - [ERROR] 新潟09R(race_id:200804010109)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010109
2022-12-24 04:05:12,924 - [ERROR] string indices must be integers
2022-12-24 04:05:12,924 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:05:18,386 - [ERROR] 新潟10R(race_id:200804010110)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010110
2022-12-24 04:05:18,386 - [ERROR] string indices must be integers
2022-12-24 04:05:18,387 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:05:23,734 - [ERROR] 新潟11R(race_id:200804010111)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010111
2022-12-24 04:05:23,735 - [ERROR] string indices must be integers
2022-12-24 04:05:23,735 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:05:29,103 - [ERROR] 新潟12R(race_id:200804010112)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200804010112
2022-12-24 04:05:29,103 - [ERROR] string indices must be integers
2022-12-24 04:05:29,103 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 04:05:34,711 - [INFO] 2008/04/27のレースデータの取得を開始します
2022-12-24 04:05:36,851 - [INFO] 取得レース数：36
2022-12-24 04:08:42,508 - [INFO] 2008/04/26のレースデータの取得を開始します
2022-12-24 04:08:44,651 - [INFO] 取得レース数：36
2022-12-24 04:11:50,562 - [INFO] 2008/04/20のレースデータの取得を開始します
2022-12-24 04:11:52,713 - [INFO] 取得レース数：36
2022-12-24 04:14:58,693 - [INFO] 2008/04/19のレースデータの取得を開始します
2022-12-24 04:15:00,802 - [INFO] 取得レース数：36
2022-12-24 04:18:07,684 - [INFO] 2008/04/13のレースデータの取得を開始します
2022-12-24 04:18:09,793 - [INFO] 取得レース数：36
2022-12-24 04:21:16,075 - [INFO] 2008/04/12のレースデータの取得を開始します
2022-12-24 04:21:18,186 - [INFO] 取得レース数：36
2022-12-24 04:24:24,648 - [INFO] 2008/04/06のレースデータの取得を開始します
2022-12-24 04:24:26,737 - [INFO] 取得レース数：24
2022-12-24 04:26:31,118 - [INFO] 2008/04/05のレースデータの取得を開始します
2022-12-24 04:26:33,245 - [INFO] 取得レース数：24
2022-12-24 04:28:37,734 - [INFO] 2008/03/30のレースデータの取得を開始します
2022-12-24 04:28:39,847 - [INFO] 取得レース数：36
2022-12-24 04:31:47,623 - [INFO] 2008/03/29のレースデータの取得を開始します
2022-12-24 04:31:49,761 - [INFO] 取得レース数：36
2022-12-24 04:34:57,237 - [INFO] 2008/03/23のレースデータの取得を開始します
2022-12-24 04:34:59,353 - [INFO] 取得レース数：36
2022-12-24 04:38:05,796 - [INFO] 2008/03/22のレースデータの取得を開始します
2022-12-24 04:38:07,942 - [INFO] 取得レース数：36
2022-12-24 04:41:14,071 - [INFO] 2008/03/16のレースデータの取得を開始します
2022-12-24 04:41:16,209 - [INFO] 取得レース数：36
2022-12-24 04:44:21,191 - [INFO] 2008/03/15のレースデータの取得を開始します
2022-12-24 04:44:23,301 - [INFO] 取得レース数：36
2022-12-24 04:47:29,591 - [INFO] 2008/03/09のレースデータの取得を開始します
2022-12-24 04:47:31,702 - [INFO] 取得レース数：36
2022-12-24 04:50:37,445 - [INFO] 2008/03/08のレースデータの取得を開始します
2022-12-24 04:50:39,564 - [INFO] 取得レース数：36
2022-12-24 04:53:44,697 - [INFO] 2008/03/02のレースデータの取得を開始します
2022-12-24 04:53:46,833 - [INFO] 取得レース数：36
2022-12-24 04:56:53,129 - [INFO] 2008/03/01のレースデータの取得を開始します
2022-12-24 04:56:55,236 - [INFO] 取得レース数：36
2022-12-24 05:00:00,657 - [INFO] 2008/02/24のレースデータの取得を開始します
2022-12-24 05:00:02,771 - [INFO] 取得レース数：23
2022-12-24 05:02:02,862 - [INFO] 2008/02/23のレースデータの取得を開始します
2022-12-24 05:02:04,978 - [INFO] 取得レース数：24
2022-12-24 05:04:09,718 - [INFO] 2008/02/17のレースデータの取得を開始します
2022-12-24 05:04:11,831 - [INFO] 取得レース数：24
2022-12-24 05:06:17,195 - [INFO] 2008/02/16のレースデータの取得を開始します
2022-12-24 05:06:19,313 - [INFO] 取得レース数：24
2022-12-24 05:08:25,391 - [INFO] 2008/02/11のレースデータの取得を開始します
2022-12-24 05:08:27,509 - [INFO] 取得レース数：24
2022-12-24 05:09:30,605 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,606 - [ERROR] '3'
2022-12-24 05:09:30,606 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '3'

2022-12-24 05:09:30,607 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,608 - [ERROR] '4'
2022-12-24 05:09:30,608 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '4'

2022-12-24 05:09:30,609 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,610 - [ERROR] '5'
2022-12-24 05:09:30,610 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '5'

2022-12-24 05:09:30,611 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,612 - [ERROR] '6'
2022-12-24 05:09:30,612 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '6'

2022-12-24 05:09:30,614 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,614 - [ERROR] '7'
2022-12-24 05:09:30,614 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '7'

2022-12-24 05:09:30,616 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,616 - [ERROR] '8'
2022-12-24 05:09:30,616 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '8'

2022-12-24 05:09:30,618 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,618 - [ERROR] '9'
2022-12-24 05:09:30,618 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '9'

2022-12-24 05:09:30,620 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,620 - [ERROR] '10'
2022-12-24 05:09:30,620 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '10'

2022-12-24 05:09:30,622 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,622 - [ERROR] '11'
2022-12-24 05:09:30,622 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '11'

2022-12-24 05:09:30,624 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,624 - [ERROR] '12'
2022-12-24 05:09:30,624 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '12'

2022-12-24 05:09:30,626 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,626 - [ERROR] '13'
2022-12-24 05:09:30,626 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '13'

2022-12-24 05:09:30,628 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,628 - [ERROR] '14'
2022-12-24 05:09:30,628 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '14'

2022-12-24 05:09:30,630 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,630 - [ERROR] '15'
2022-12-24 05:09:30,630 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '15'

2022-12-24 05:09:30,632 - [ERROR] 京都01R(race_id:200808020301)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020301
2022-12-24 05:09:30,632 - [ERROR] '16'
2022-12-24 05:09:30,632 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '16'

2022-12-24 05:09:35,660 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,661 - [ERROR] '3'
2022-12-24 05:09:35,661 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '3'

2022-12-24 05:09:35,663 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,663 - [ERROR] '4'
2022-12-24 05:09:35,663 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '4'

2022-12-24 05:09:35,665 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,665 - [ERROR] '5'
2022-12-24 05:09:35,665 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '5'

2022-12-24 05:09:35,667 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,667 - [ERROR] '6'
2022-12-24 05:09:35,667 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '6'

2022-12-24 05:09:35,669 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,669 - [ERROR] '7'
2022-12-24 05:09:35,669 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '7'

2022-12-24 05:09:35,671 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,671 - [ERROR] '8'
2022-12-24 05:09:35,671 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '8'

2022-12-24 05:09:35,673 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,673 - [ERROR] '9'
2022-12-24 05:09:35,673 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '9'

2022-12-24 05:09:35,675 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,675 - [ERROR] '10'
2022-12-24 05:09:35,675 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '10'

2022-12-24 05:09:35,677 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,677 - [ERROR] '11'
2022-12-24 05:09:35,677 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '11'

2022-12-24 05:09:35,679 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,679 - [ERROR] '12'
2022-12-24 05:09:35,679 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '12'

2022-12-24 05:09:35,681 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,681 - [ERROR] '13'
2022-12-24 05:09:35,681 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '13'

2022-12-24 05:09:35,683 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,683 - [ERROR] '14'
2022-12-24 05:09:35,683 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '14'

2022-12-24 05:09:35,685 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,685 - [ERROR] '15'
2022-12-24 05:09:35,685 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '15'

2022-12-24 05:09:35,687 - [ERROR] 京都02R(race_id:200808020302)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020302
2022-12-24 05:09:35,687 - [ERROR] '16'
2022-12-24 05:09:35,687 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '16'

2022-12-24 05:15:51,468 - [INFO] 2008/02/03のレースデータの取得を開始します
2022-12-24 05:15:53,558 - [INFO] 取得レース数：23
2022-12-24 05:15:56,196 - [ERROR] 京都01R(race_id:200808020201)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020201
2022-12-24 05:15:56,196 - [ERROR] string indices must be integers
2022-12-24 05:15:56,196 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:16:06,105 - [ERROR] 京都03R(race_id:200808020203)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020203
2022-12-24 05:16:06,105 - [ERROR] string indices must be integers
2022-12-24 05:16:06,105 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:16:21,294 - [ERROR] 京都07R(race_id:200808020207)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020207
2022-12-24 05:16:21,294 - [ERROR] string indices must be integers
2022-12-24 05:16:21,294 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:16:41,588 - [ERROR] 京都11R(race_id:200808020211)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020211
2022-12-24 05:16:41,588 - [ERROR] string indices must be integers
2022-12-24 05:16:41,588 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:16:47,116 - [ERROR] 京都12R(race_id:200808020212)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020212
2022-12-24 05:16:47,116 - [ERROR] string indices must be integers
2022-12-24 05:16:47,116 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:17:54,848 - [INFO] 2008/02/02のレースデータの取得を開始します
2022-12-24 05:17:56,984 - [INFO] 取得レース数：36
2022-12-24 05:19:00,289 - [ERROR] 京都01R(race_id:200808020101)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020101
2022-12-24 05:19:00,289 - [ERROR] string indices must be integers
2022-12-24 05:19:00,289 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:19:05,398 - [ERROR] 京都02R(race_id:200808020102)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020102
2022-12-24 05:19:05,399 - [ERROR] string indices must be integers
2022-12-24 05:19:05,399 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:19:25,952 - [ERROR] 京都06R(race_id:200808020106)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020106
2022-12-24 05:19:25,953 - [ERROR] string indices must be integers
2022-12-24 05:19:25,953 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:19:36,531 - [ERROR] 京都08R(race_id:200808020108)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020108
2022-12-24 05:19:36,531 - [ERROR] string indices must be integers
2022-12-24 05:19:36,531 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:19:47,097 - [ERROR] 京都10R(race_id:200808020110)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020110
2022-12-24 05:19:47,097 - [ERROR] string indices must be integers
2022-12-24 05:19:47,097 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:19:52,713 - [ERROR] 京都11R(race_id:200808020111)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020111
2022-12-24 05:19:52,713 - [ERROR] string indices must be integers
2022-12-24 05:19:52,714 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:19:58,083 - [ERROR] 京都12R(race_id:200808020112)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808020112
2022-12-24 05:19:58,083 - [ERROR] string indices must be integers
2022-12-24 05:19:58,083 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:21:05,686 - [INFO] 2008/01/27のレースデータの取得を開始します
2022-12-24 05:21:07,831 - [INFO] 取得レース数：36
2022-12-24 05:22:51,274 - [ERROR] 京都09R(race_id:200808010809)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808010809
2022-12-24 05:22:51,274 - [ERROR] string indices must be integers
2022-12-24 05:22:51,275 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:22:56,425 - [ERROR] 京都10R(race_id:200808010810)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808010810
2022-12-24 05:22:56,426 - [ERROR] string indices must be integers
2022-12-24 05:22:56,426 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:23:02,002 - [ERROR] 京都11R(race_id:200808010811)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808010811
2022-12-24 05:23:02,002 - [ERROR] string indices must be integers
2022-12-24 05:23:02,002 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:23:07,394 - [ERROR] 京都12R(race_id:200808010812)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200808010812
2022-12-24 05:23:07,394 - [ERROR] string indices must be integers
2022-12-24 05:23:07,394 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:24:13,982 - [INFO] 2008/01/26のレースデータの取得を開始します
2022-12-24 05:24:16,116 - [INFO] 取得レース数：36
2022-12-24 05:27:21,280 - [INFO] 2008/01/20のレースデータの取得を開始します
2022-12-24 05:27:23,394 - [INFO] 取得レース数：36
2022-12-24 05:30:30,587 - [INFO] 2008/01/19のレースデータの取得を開始します
2022-12-24 05:30:32,699 - [INFO] 取得レース数：36
2022-12-24 05:33:38,030 - [INFO] 2008/01/13のレースデータの取得を開始します
2022-12-24 05:33:40,121 - [INFO] 取得レース数：24
2022-12-24 05:35:45,677 - [INFO] 2008/01/12のレースデータの取得を開始します
2022-12-24 05:35:47,766 - [INFO] 取得レース数：24
2022-12-24 05:35:50,265 - [ERROR] 中山01R(race_id:200806010301)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010301
2022-12-24 05:35:50,265 - [ERROR] string indices must be integers
2022-12-24 05:35:50,265 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:35:55,508 - [ERROR] 中山02R(race_id:200806010302)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010302
2022-12-24 05:35:55,508 - [ERROR] string indices must be integers
2022-12-24 05:35:55,508 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:36:10,854 - [ERROR] 中山05R(race_id:200806010305)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010305
2022-12-24 05:36:10,854 - [ERROR] string indices must be integers
2022-12-24 05:36:10,854 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:36:26,640 - [ERROR] 中山08R(race_id:200806010308)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010308
2022-12-24 05:36:26,640 - [ERROR] string indices must be integers
2022-12-24 05:36:26,640 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:37:55,387 - [INFO] 2008/01/06のレースデータの取得を開始します
2022-12-24 05:37:57,480 - [INFO] 取得レース数：24
2022-12-24 05:38:00,202 - [ERROR] 中山01R(race_id:200806010201)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010201
2022-12-24 05:38:00,202 - [ERROR] string indices must be integers
2022-12-24 05:38:00,202 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:38:05,636 - [ERROR] 中山02R(race_id:200806010202)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010202
2022-12-24 05:38:05,636 - [ERROR] string indices must be integers
2022-12-24 05:38:05,636 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:38:20,918 - [ERROR] 中山05R(race_id:200806010205)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010205
2022-12-24 05:38:20,918 - [ERROR] string indices must be integers
2022-12-24 05:38:20,918 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:38:31,258 - [ERROR] 中山07R(race_id:200806010207)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010207
2022-12-24 05:38:31,259 - [ERROR] string indices must be integers
2022-12-24 05:38:31,259 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:38:41,850 - [ERROR] 中山09R(race_id:200806010209)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010209
2022-12-24 05:38:41,850 - [ERROR] string indices must be integers
2022-12-24 05:38:41,850 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:38:47,132 - [ERROR] 中山10R(race_id:200806010210)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010210
2022-12-24 05:38:47,132 - [ERROR] string indices must be integers
2022-12-24 05:38:47,133 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:38:52,365 - [ERROR] 中山11R(race_id:200806010211)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010211
2022-12-24 05:38:52,365 - [ERROR] string indices must be integers
2022-12-24 05:38:52,365 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:38:57,750 - [ERROR] 中山12R(race_id:200806010212)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010212
2022-12-24 05:38:57,750 - [ERROR] string indices must be integers
2022-12-24 05:38:57,750 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:40:04,200 - [INFO] 2008/01/05のレースデータの取得を開始します
2022-12-24 05:40:06,322 - [INFO] 取得レース数：24
2022-12-24 05:40:08,996 - [ERROR] 中山01R(race_id:200806010101)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010101
2022-12-24 05:40:08,996 - [ERROR] string indices must be integers
2022-12-24 05:40:08,996 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:40:14,505 - [ERROR] 中山02R(race_id:200806010102)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010102
2022-12-24 05:40:14,505 - [ERROR] string indices must be integers
2022-12-24 05:40:14,505 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:40:19,808 - [ERROR] 中山03R(race_id:200806010103)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010103
2022-12-24 05:40:19,808 - [ERROR] string indices must be integers
2022-12-24 05:40:19,808 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:40:25,268 - [ERROR] 中山04R(race_id:200806010104)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010104
2022-12-24 05:40:25,268 - [ERROR] string indices must be integers
2022-12-24 05:40:25,268 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:40:30,733 - [ERROR] 中山05R(race_id:200806010105)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010105
2022-12-24 05:40:30,734 - [ERROR] string indices must be integers
2022-12-24 05:40:30,734 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:40:36,002 - [ERROR] 中山06R(race_id:200806010106)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010106
2022-12-24 05:40:36,003 - [ERROR] string indices must be integers
2022-12-24 05:40:36,003 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:40:41,431 - [ERROR] 中山07R(race_id:200806010107)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010107
2022-12-24 05:40:41,431 - [ERROR] string indices must be integers
2022-12-24 05:40:41,432 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:40:46,862 - [ERROR] 中山08R(race_id:200806010108)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010108
2022-12-24 05:40:46,862 - [ERROR] string indices must be integers
2022-12-24 05:40:46,862 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:40:52,274 - [ERROR] 中山09R(race_id:200806010109)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010109
2022-12-24 05:40:52,274 - [ERROR] string indices must be integers
2022-12-24 05:40:52,274 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:40:57,534 - [ERROR] 中山10R(race_id:200806010110)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010110
2022-12-24 05:40:57,534 - [ERROR] string indices must be integers
2022-12-24 05:40:57,534 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:41:02,868 - [ERROR] 中山11R(race_id:200806010111)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010111
2022-12-24 05:41:02,868 - [ERROR] string indices must be integers
2022-12-24 05:41:02,868 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers

2022-12-24 05:41:08,354 - [ERROR] 中山12R(race_id:200806010112)のオッズ取得APIでエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200806010112
2022-12-24 05:41:08,355 - [ERROR] string indices must be integers
2022-12-24 05:41:08,355 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 315, in get_umabashira
    odds_list = self.get_odds_list()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 672, in get_odds_list
    odds = odds_dict['data']['odds']['1']
TypeError: string indices must be integers


2022-12-24 09:54:09,069 - [INFO] 2007/10/27のレースデータの取得を開始します
2022-12-24 09:54:11,184 - [INFO] 取得レース数：36
2022-12-24 09:56:04,631 - [ERROR] 京都11R(race_id:200708040811)のオッズ追加処理でエラー
https://race.netkeiba.com/race/shutuba_past.html?race_id=200708040811
2022-12-24 09:56:04,631 - [ERROR] '18'
2022-12-24 09:56:04,631 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 430, in get_umabashira
    if odds_list[str(i + 1)][0] != '-3.0' and odds_list[str(i + 1)][0] != '-2.0':
KeyError: '18'

2022-12-24 10:20:13,783 - [INFO] 2007/09/23のレースデータの取得を開始します
2022-12-24 10:20:15,925 - [INFO] 取得レース数：36
2022-12-24 10:21:56,879 - [ERROR] 阪神08R(race_id:200709040608)のレース結果取得処理でエラー
2022-12-24 10:21:56,879 - [ERROR] '16'
2022-12-24 10:21:56,879 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 529, in get_result
    self.horse_race_info_dict[str(row['馬番'])].jockey_handi = '▲'
KeyError: '16'

2022-12-24 10:23:20,813 - [INFO] 2007/09/22のレースデータの取得を開始します
2022-12-24 10:23:22,970 - [INFO] 取得レース数：36
2022-12-24 10:23:38,393 - [ERROR] 中山03R(race_id:200706040503)のレース結果取得処理でエラー
2022-12-24 10:23:38,393 - [ERROR] '16'
2022-12-24 10:23:38,393 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '16'

2022-12-24 10:26:27,780 - [INFO] 2007/09/17のレースデータの取得を開始します
2022-12-24 10:26:29,894 - [INFO] 取得レース数：24
2022-12-24 10:28:33,893 - [INFO] 2007/09/16のレースデータの取得を開始します
2022-12-24 10:28:36,013 - [INFO] 取得レース数：24
2022-12-24 10:30:06,922 - [ERROR] 阪神06R(race_id:200709040306)のレース結果取得処理でエラー
2022-12-24 10:30:06,922 - [ERROR] '12'
2022-12-24 10:30:06,922 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '12'

2022-12-24 10:42:07,350 - [INFO] 2007/09/01のレースデータの取得を開始します
2022-12-24 10:42:09,481 - [INFO] 取得レース数：36
2022-12-24 10:43:31,463 - [ERROR] 小倉04R(race_id:200710030704)のレース結果取得処理でエラー
2022-12-24 10:43:31,463 - [ERROR] '18'
2022-12-24 10:43:31,463 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '18'

2022-12-24 10:45:15,907 - [INFO] 2007/08/26のレースデータの取得を開始します
2022-12-24 10:45:18,139 - [INFO] 取得レース数：36
2022-12-24 10:46:55,415 - [ERROR] 小倉07R(race_id:200710030607)のレース結果取得処理でエラー
2022-12-24 10:46:55,415 - [ERROR] '18'
2022-12-24 10:46:55,415 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 529, in get_result
    self.horse_race_info_dict[str(row['馬番'])].jockey_handi = '▲'
KeyError: '18'

2022-12-24 10:48:24,594 - [INFO] 2007/08/25のレースデータの取得を開始します
2022-12-24 10:48:26,727 - [INFO] 取得レース数：36
2022-12-24 10:48:41,812 - [ERROR] 新潟03R(race_id:200704030503)のレース結果取得処理でエラー
2022-12-24 10:48:41,813 - [ERROR] '18'
2022-12-24 10:48:41,813 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 595, in get_result
    horse_result.horse_id = self.horse_race_info_dict[str(row['馬番'])].horse_id
KeyError: '18'

2022-12-24 10:51:42,067 - [INFO] 2007/08/12のレースデータの取得を開始します
2022-12-24 10:51:44,270 - [INFO] 取得レース数：36
2022-12-24 10:53:20,260 - [ERROR] 小倉07R(race_id:200710030207)のレース結果取得処理でエラー
2022-12-24 10:53:20,260 - [ERROR] '16'
2022-12-24 10:53:20,261 - [ERROR] Traceback (most recent call last):
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 103, in main
    self.get_result()
  File "/home/poi/keibaai/src/scraping/pastjraracedata.py", line 529, in get_result
    self.horse_race_info_dict[str(row['馬番'])].jockey_handi = '▲'
KeyError: '16'
